# The basic colors
foreground              #e0e0e0
background              #121212
selection_foreground    #121212
selection_background    #bdbdbd

# Cursor colors
cursor                  #ffffff
cursor_text_color       #121212

# URL underline color
url_color               #616161

# Window border colors
active_border_color     #ffffff
inactive_border_color   #424242
bell_border_color       #ffca28

# Tab bar colors
active_tab_foreground   #121212
active_tab_background   #ffffff
inactive_tab_foreground #bdbdbd
inactive_tab_background #212121
tab_bar_background      #121212

# The 16 terminal colors

# black (grays)
color0  #212121
color8  #616161

# red (blood accent)
color1  #d32f2f
color9  #ef5350

# green (muted)
color2  #2e7d32
color10 #66bb6a

# yellow (Shinigami accent)
color3  #ffb300
color11 #ffca28

# blue (muted)
color4  #0d47a1
color12 #42a5f5

# magenta (Death Note purple)
color5  #6a1b9a
color13 #ab47bc

# cyan (muted)
color6  #006064
color14 #26c6da

# white (text colors)
color7  #e0e0e0
color15 #ffffff
