#!/bin/sh
# =============================================================
# Script to control prefered apps to launch for all themes
# Author:  z0mbi3
# Repo:    https://github.com/gh0stzk/dotfiles
# Date:    24.04.2025
# Copyright (C) 2021-2025 gh0stzk <z0mbi3.zk@protonmail.com>
# Licensed under GPL-3.0 license
# =============================================================

WIDGET_DIR="$HOME/.config/bspwm/eww"

case "$1" in
	--menu)
		RofiLauncher --launcher
		;;
	--terminal)
		Term --terminal
		;;
	--floating)
		Term --floating
		;;
	--update)
		Term --update
		;;
	--checkupdates)
		Term --checkupdates
		;;
	--clipboard)
		clipcat-menu
		;;
	--screenshot)
		ScreenShoTer
		;;
	--powermenu)
		PowerMenu
		;;
	--keyboard)
		KeyBoardL
		;;
	--yazi)
		Term --yazi
		;;
	--nvim)
		Term --nvim
		;;
	--fetch)
		Term --fetch
		;;
  --scratch)
		Bspwm-ScratchPad
		;;
		# Apps
	--filemanager)
		thunar
		;;
	--browser)
		firefox
		;;
	--soundcontrol)
		pavucontrol
		;;
		# Eww Widgets
	--usercard)
		eww -c "$WIDGET_DIR" open --toggle launchermenu
		;;
	--calendar)
		eww -c "$WIDGET_DIR" open --toggle date
		;;
	*)
		echo "Invalid Option"
		;;
esac
